
export const dynamic = "force-dynamic"
import { NextRequest, NextResponse } from 'next/server'
import { createGuardedHandler } from '@/lib/security/guards'
import { checkUsageLimit, incrementUsage } from '@/lib/usage'
import { hasFeatureAccess } from '@/lib/auth'
import { callAIService } from '@/lib/ai-service'

export const POST = createGuardedHandler(
  async (request: NextRequest, { auth }) => {
    const { contractText } = await request.json()
    const userId = auth.user.id

    if (!contractText) {
      return NextResponse.json({ error: 'Contract text is required' }, { status: 400 })
    }

    if (!hasFeatureAccess(auth.user, 'DOC_GENERATOR')) {
      return NextResponse.json({
        error: 'Contract review not available in your plan. Upgrade to access this feature.'
      }, { status: 403 })
    }

    const usageCheck = await checkUsageLimit(userId, 'DOC_GENERATOR')
    if (!usageCheck.allowed) {
      return NextResponse.json({
        error: 'Usage limit reached',
        reason: usageCheck.reason
      }, { status: 402 })
    }

    console.log('Reviewing contract with NVIDIA AI...')

    try {
      const response = await callAIService([
        {
          role: 'system',
          content: 'You are a professional contract review specialist. Provide detailed analysis in a structured format.'
        },
        {
          role: 'user',
          content: `Please review the following contract and provide a detailed analysis:
      
      CONTRACT TEXT:
      ${contractText.substring(0, 8000)}
      
      Please provide a comprehensive review in the following format:
      
      ## CONTRACT OVERVIEW
      [Type of contract and its main purpose]
      
      ## KEY TERMS ANALYSIS
      [Analysis of important terms, conditions, and clauses]
      
      ## FINANCIAL OBLIGATIONS
      [Payment terms, amounts, penalties, and financial responsibilities]
      
      ## RIGHTS AND RESPONSIBILITIES
      [What each party is obligated to do and their rights]
      
      ## RISK ASSESSMENT
      [Potential legal risks or unfavorable terms]
      
      ## COMPLIANCE & LEGAL ISSUES
      [Legal compliance concerns or regulatory requirements]
      
      ## TERMINATION & DISPUTE RESOLUTION
      [How the contract can be terminated and how disputes are handled]
      
      ## RECOMMENDATIONS
      [Specific suggestions for improvements or negotiations]
      
      ## MISSING ELEMENTS
      [Important clauses or terms that should be added]
      
      ## OVERALL ASSESSMENT
      [Summary rating and key takeaways]
      
      Please be thorough and include a disclaimer about seeking professional legal counsel.`
        }
      ], auth.user.plan || 'FREE', 4096)

      if (!response.content) {
        throw new Error('No analysis generated by AI')
      }

      await incrementUsage(userId, 'DOC_GENERATOR')

      return NextResponse.json({ review: response.content })

    } catch (error) {
      console.error('Contract Review Error:', error)
      return NextResponse.json({ error: 'AI service unavailable' }, { status: 503 })
    }
  },
  { requireAuth: true, requireCSRF: true }
)