import { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Disclaimer | LAW.AI',
    description: 'Legal Disclaimer for LAW.AI',
}

export default function DisclaimerPage() {
    return (
        <div className="max-w-4xl mx-auto px-4 py-12 sm:px-6 lg:px-8">
            <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-sm p-8 md:p-12 border border-gray-100 dark:border-gray-700">
                <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-8">Legal Disclaimer</h1>

                <div className="prose prose-lg dark:prose-invert max-w-none">
                    <div className="bg-yellow-50 dark:bg-yellow-900/30 border-l-4 border-yellow-400 p-4 mb-8 not-prose">
                        <p className="text-sm text-yellow-800 dark:text-yellow-200 m-0 font-semibold">
                            CRITICAL NOTICE: LAW.AI is an Artificial Intelligence tool. It is NOT a lawyer, law firm, or a substitute for professional legal advice.
                        </p>
                    </div>

                    <h2>1. No Attorney-Client Relationship</h2>
                    <p>
                        Use of LAW.AI does not create an attorney-client relationship between you and LAW.AI (or RAGSPRO).
                        The information generated by our AI models is for educational and research purposes only.
                        Do not rely on it as legal advice for any real-world legal matter without consulting a qualified advocate.
                    </p>

                    <h2>2. Accuracy of Information</h2>
                    <p>
                        While we strive to keep our AI models updated with the latest Indian laws (BNS, BNSS, BSA, etc.), legal information changes rapidly.
                        We do not guarantee the accuracy, completeness, or currency of any information generated by the AI.
                        Always verify citations and legal provisions with official government gazettes or a legal professional.
                    </p>

                    <h2>3. "As Is" Basis</h2>
                    <p>
                        The Service and all content are provided on an "as is" and "as available" basis without any warranties of any kind,
                        either express or implied, including but not limited to warranties of merchantability or fitness for a particular purpose.
                    </p>

                    <h2>4. Limitation of Liability</h2>
                    <p>
                        You agree that you bear all risks associated with the use of any content made available through the Service.
                        You acknowledge that LAW.AI is not liable for any direct, indirect, incidental, or consequential damages resulting from
                        your use or inability to use the Service or for cost of procurement of substitute services.
                    </p>
                </div>
            </div>
        </div>
    )
}
